name: Publish angular-storybook to Chromatic
on:
  push:
    branches:
      - main
    # 👇 Filter paths for the specific project
    paths:
      - 'apps/angular-storybook/**'

jobs:
  publish-to-chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Setup bun
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      # Runs builds project and deploy to chromatic
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          # 👇 Chromatic projectToken for the specific project
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_ANGULAR_STORYBOOK }}
          # 👇 Working directory for the specific project
          workingDir: apps/angular-storybook
          # Telling chromatic to use bun to build the project
          buildCommand: bun run build-storybook
          # Required output directory when using buildCommand
          outputDir: storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
