name: Publish react-storybook to Chromatic
on:
  push:
    branches:
      - main
    paths:
      - 'apps/react-storybook/**'

jobs:
  publish-to-chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # Setup bun
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      # Goes to the correct workspace
      - run: cd apps/react-storybook
      # Deploys to chromatic
      # 👇 Remember to change the variable name for the next project/app
#      - run: bunx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN_REACT_STORYBOOK }}
      # Runs builds project and deploy to chromatic
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          # 👇 Chromatic projectToken for the specific project
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_REACT_STORYBOOK }}
          # 👇 Working directory
          workingDir: apps/react-storybook
          # Telling chromatic to use bun to build the project
          buildCommand: bun run build-storybook
          # Required output directory when using buildCommand
          outputDir: storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
